### ISSUE TITLE
feature: Divide/divmmc (esxdos support)

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/ZX-Spectrum_MISTer#15]
ESXDos gives nice features to the spectrum, it would be great to have them.

**Comment by sorgelig** [comment]
It's kind of experience breaking add-on. It locks ZX-Spectrum to ZX48 interface. Besides that it uses direct SD card access so it will require VHD container. You won't be able simply put your game to SD card. You will have to open VHD image in some application to add more files there.
At the end it adds almost nothing to features. 
DivMMC was developed for real HW to replace slow and bulky FDD. MiSTer has no such problems. It already emulates FDD at more compatible level than DivMMC.

**Comment by jsmolina** [comment]
thanks for your reply

There are some games (ianna) or commands in exdos (for playing video, scl2trd, ...) that create a nice experience.  
Having a vhd would be totally ok and nice, and might help us to test newer versions of esxdos in a closer to hardware environment.

If you haven't tested it, I would recommend you zesarux emulator, which supports esxdos nicely.

**Comment by sorgelig** [comment]
SCL is already supported by core

**Comment by jsmolina** [comment]
ok! let's close it.

good work anyway, thanks for your efforts!
