### ISSUE TITLE
Kempston mouse support?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/ZX-Spectrum_MISTer#17]
It would be great to have kempston mouse support either on this one or zx evo core.

There are a few games and conversions for it.

The best one is 'ZX Larry', appeared on latest ZX Dev, but there are others:
https://velesoft.speccy.cz/kmsoft.htm

and probably much more.

It's kind of BSX on SNES, it's not a veeery used feature, but a nice one 😄

**Comment by sorgelig** [comment]
kempston mouse is already supported

**Comment by jsmolina** [comment]
so sorry! it didn't work in zx larry. 
My fault, probably.

**Comment by jsmolina** [comment]
I'm reopening as I can't find a way to make mouse work, I tried many games.

ZX Larry
https://www.t2e.pl/pobierz/ZxLarry-t2e.pl.zip,28812,show

Lemmings
Zynaps
found on:
https://velesoft.speccy.cz/kmsoft.htm

but there was no OSD or indication to tell mouse was connected or so. 
Of course, I read the 'readme' of moving and clicking mouse asap to get detection, but no way.

**Comment by sorgelig** [comment]
ZX Larry works with mouse. Also tried 1k Arkanoid - also work.

**Comment by jsmolina** [comment]
Then it will be something on me, sorry again then.
