### ISSUE TITLE
a lot of tapes broken with current release

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/ZX-Spectrum_MISTer#20]
A lot of tapes are broken with current release V20210123. R loading Error's, hang ups during loading, or loading border goes red flashing

Just some examples of the N folder:

N.E.I.L. Android (1988)(Alternative Software).tzx
Nebula (1984)(Red Shift).tzx
Necris Dome, The (1987)(Codemasters).tzx

All these are working in previous V201108.

If more examples or md5 sums of the files are needed just tell me. I'd pick them out.

**Comment by sorgelig** [comment]
i will re-check.. similar problem was with Amstrad with latest tzxtape module, so i had to roll back to previous version. Probably i have to do it on ZX too..

**Comment by PhantombrainM** [comment]
All working again.
