### ISSUE TITLE
Port FE is not working properly

### ISSUE THREAD

**Issue by mambrino** [MiSTer-devel/ZX-Spectrum_MISTer#21]
When bit 4 (EAR output) of port FE is set to 0 or 1 and that port is read back, it should return the same status in bit 6 (EAR input) if computer is an issue 3, always 0 or 1 until bit 3 is enabled (MIC output and indirectly EAR output) and any subsequent reading of the port would return the same written value, this would be the case of an issue 2, or it would always remain fixed at 0 or 1 regardless of the status written to bit 3, which is the wrong case and the one that occurs in some emulators and this core (it always returns 1).

This is not the appropriate behaviour for this port, because it doesn't fit any of the two issues and causes problems with some games, such as abu simbel or blinkys scary school.

More details can be found here: https://worldofspectrum.org/faq/reference/48kreference.htm (Port 0xfe section)

**Comment by sorgelig** [comment]
so bit 6 = bit 4 when reading back on issue 3?

**Comment by mambrino** [comment]
yes

**Comment by sorgelig** [comment]
try this version:
[ZX-Spectrum.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6242493/ZX-Spectrum.zip)

**Comment by gyurco** [comment]
It's true when the real EAR input is low.
If bit 4 out = 0, then bit 6 input will follow the EAR input. If bit 4 out = 1, then the EAR input cannot pull down the ULA bit 6 input.
Unconnected EAR input should be 0.
On Issue 3, the MIC output doesn't really affect the ULA EAR input (bit 6), on Issue 2 it does.

**Comment by mambrino** [comment]
> try this version:
> [ZX-Spectrum.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6242493/ZX-Spectrum.zip)

now works as expected for an issue 3
thanks ;)

**Comment by mambrino** [comment]
would be possible to add issue 2 compatibility too with a menu option for switch between both issues?
Games like Abu Simbel needs issue 2 keyboard for working properly

**Comment by sorgelig** [comment]
may be issue 2 is enough then?

**Comment by mambrino** [comment]
I've been testing and with issue 2 everything should work, but I don't know if there is any specific game that requires issue 3. As far as I know only these two games are issue 2 restricted: Abu Simbel Profanation and Rasputin 48k, but 128k models are not issue 2, so they could give problems. Maybe an issue 2/3 selector would be the best solution.

**Comment by sorgelig** [comment]
ok

**Comment by mambrino** [comment]
I've tested your last release, but seems to be a problem related to issue selector. When issue 3 mode is selected tape loading works perfectly, but when you select issue 2 there's not loading at all.

**Comment by sorgelig** [comment]
what you mean by "loading"?

**Comment by mambrino** [comment]
second menu option: load tape file (tap,csw,tzx), and after input load "", virtual tape start playing but if you have issue 2 selected, seems that the spectrum doesn't receive anything from tape and stay with gray border wating for data.

**Comment by sorgelig** [comment]
i see. may be i should ignore mic out level then

**Comment by sorgelig** [comment]
try this:
[ZX-Spectrum.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6253768/ZX-Spectrum.zip)

**Comment by mambrino** [comment]
Now virtual tape works (regardless of the selected issue), but there is another problem, the disciple d+ interface can no longer write to disk. If you try to save a program from basic or dump ram to disk from snapshot menu, the core crashes. Disk loading seems to work fine.

**Comment by sorgelig** [comment]
did you update Main?

**Comment by sorgelig** [comment]
can you provide me +d simple disk with may be some test basic file and instruction how to display catalog, read and write file? I've forgot everything about +3 disk already.

**Comment by mambrino** [comment]
yes. i'm testing with latest main version. Previous testing core (posted here 3 days ago) can write perfectly.
here you have: https://filebin.net/g2uu8p5aixwgqozp/test.zip?t=t4xut717
for display catalog: CAT 1
for loading: LOAD D1 "TEST"
for writing: SAVE D1 "TEST"

**Comment by mambrino** [comment]
+3 native disk access has the same problem (reads but hangs when writing), maybe it has been affected with sd access changes from last core.

**Comment by sorgelig** [comment]
this should fix the write issue:
[MiSTer.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6254142/MiSTer.zip)

**Comment by mambrino** [comment]
now it works! thanks again ;)
