### ISSUE TITLE
Enlarge the screen to 16: 9 HDMI/remove side black bands

### ISSUE THREAD

**Issue by PakkunKinoppi** [MiSTer-devel/ZX-Spectrum_MISTer#22]
Good morning @sorgelig ,
is there the possibility to enlarge the screen to 16: 9?
I would like to eliminate the two black side bands that appear (see photo), other cores have the option in the menu but with the ZxSpectrum core I can't find a way to have a full screen without these two side black bands.
How can I do?

![Untitled 1](https://user-images.githubusercontent.com/52820759/115187653-f8601980-a0e3-11eb-8c19-49991d39faff.jpg)

**Comment by sorgelig** [comment]
core follows the aspect ratio of original system. You may add custom aspect ratios in INI if you want to modify aspect ratio and expand it to full 16:9 screen.

**Comment by PakkunKinoppi** [comment]
Do you mean the mister.ini ?
This one ? 

;
; custom mode: hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;   video_mode=1280,110,40,220,720,5,5,20,74250
**video_mode=0**

or this one :
; Custom aspect ratio
;custom_aspect_ratio_1=16:10
;custom_aspect_ratio_2=1:1

but in this second case there is not the keyword in red to be changed (command?) 

_Could you write me an example ...  please ?_
Thanks

**Comment by sorgelig** [comment]
Actually you can choose simple "full screen" aspect ratio from OSD.

**Comment by PakkunKinoppi** [comment]
Ok, Core updated ...it works fully screen from OSD.
Great !!!

Thank you!
