### ISSUE TITLE
Z80 Cpu test fail

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#23]
@sorgelig 
Hi, some cpu tests fail, on PC/mac fuse  emulator they seem to work fine (all .tap tests).

Here they are:
[z80test.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6409095/z80test.zip)

![image0 (1)](https://user-images.githubusercontent.com/34916641/116775576-f131f780-aa63-11eb-8bab-2c17f290b084.jpeg)

**Comment by sorgelig** [comment]
CCF/SCF XY flags aren't fully implemented and probably will never be. There is no known software use such undocumented behavior, but amount of work for this useless feature is enormous. 
Even real CPUs fail CCF/SCF XY flags depending on manufacturer.

**Comment by sorgelig** [comment]
actually you need to use z80full.tap
It's passed except 2 SCF/CCF because of undocumented XY flags. SCF and CCF themseves are fully correct in documented ways.
Undocumented XY flags for other instructions are also fully correct.

**Comment by Alessandro1970** [comment]
Ok
