### ISSUE TITLE
IRContention test fails

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#24]
@sorgelig 

This test doesn't work as expected.

[IRContention.tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6409110/IRContention.tap.zip)

**Comment by sorgelig** [comment]
please elaborate it more clearly.
This test is fully correct on core. I've used this test to tweak the core.

**Comment by Alessandro1970** [comment]
I haven't used the right configuration on Mister so the demo was wrong.
