### ISSUE TITLE
Esi Shock Megademo has some problem

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#25]
@sorgelig 
 
[Shock.tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6409128/Shock.tap.zip)

This demo does not work well in this screen, there are some bugs:
![Schermata 2021-05-01 alle 10 13 51](https://user-images.githubusercontent.com/34916641/116775900-f728d800-aa65-11eb-85ce-5b51df5195c3.png)

**Comment by sorgelig** [comment]
1) when you report bug, please show photo/video from MiSTer, not from emulator
2) Use ULA-128 and Spectrum 128K memory config. It will work OK.
Demo somehow detects Spectrum 48K mode as 128K and sets ULA-128 timings.

**Comment by Alessandro1970** [comment]
Probably I used not the right configuration on Mister.
