### ISSUE TITLE
Megademo hangs

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#26]
Megademo DRDF099 hangs at first screen

[Megademo (1991)(DrDF0).tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6409146/Megademo.1991.DrDF0.tap.zip)

**Comment by sorgelig** [comment]
if it hangs on loading then you are not correctly loaded it.
Many games/demos on Spectrum 128K don't like Tape Loader from 128K menu. You need to type USR0 from basic to go to 48K basic and then load from there. It's not a core issue. It's original Spectrum 128K issue.
ON MiSTer you can simply press F10 to automate tape loading.

**Comment by Alessandro1970** [comment]
Ok, thanks
