### ISSUE TITLE
Save core settings

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#27]
@sorgelig

hi, when I change the core settings (full screen or memory) the core does not let me to save it.
So when I turn on the mister the settings are lost and are to be changed again.
The same with c64 core.
Can you let the users to save the settings for each core ?
A new command in the core menu to save settings as default, I mean.
Thank you

**Comment by sorgelig** [comment]
OSD settings are saved in System->Save Settings. There you can also find "reset settings" option.
If settings aren't saved for you, then something wrong with your setup. May be some corruption if file system.

**Comment by Alessandro1970** [comment]
Formatted an re-installed the SD, now it works !
Thanks
