### ISSUE TITLE
How to assign a key permanently

### ISSUE THREAD

**Issue by puleyo** [MiSTer-devel/ZX-Spectrum_MISTer#28]
@sorgelig 

hi,
I need to change a key, how can I modify the keymap permanently ?
Is there a file to edit ?
If I change a key by menu when I reload the core it will be restored to default., I need to  fix it permanently, the save setting does not work for this.
Help me please.
Thanks

**Comment by sorgelig** [comment]
If you mean "remap button for a game" then it's supposed to be temporary. It cannot be saved. Different game may use different keys and core doesn't distinguish games, so it cannot be saved.

**Comment by puleyo** [comment]
I’m seeking for a permanent solution, not for a game, I need to adapt my keyboard for this Zx core.
Is it possible ?

**Comment by sorgelig** [comment]
it's possible at some extent. Actually ZX keyboard is a subset of PC keyboard in the core. So you just use only keys exist on ZX. Beside ZX keys some system keys are required like F12, cursor keys. Other F keys are also used for extra core functions.

As for key remap you need to go to Manu core and there you will find keyboard remap option. It's persistent across all cores. But it works only key to key remap. You cannot remap combo to key or key to combo.

**Comment by midicdj1000** [comment]
HI, I am making a Spectrum +2a keyboard to USB converter with a PI pico and was wondering if you have a full keymap, I couldn't find one in the docs. How does the core work with keys like true video , inverted video , edit, graph ? what are the normal key board keys for this.

**Comment by sorgelig** [comment]
MiSTer is multi-core system, so it's build around standard input devices such as PC AT 104-key keyboard. Spectrum keyboard is reduced one, so it won't fit to all cores, especially computer cores. Mappings keyboard to each computer core are different according to specific needs. If you are talking about mapping only for ZX core, then it's mostly straight.. Basically alpha-numeric keys with automatic combo activation for extended keys such as cursor keys. Fn keys are mentioned in ZX core readme.

**Comment by midicdj1000** [comment]
I am making a usb keyboard to match the core as close as possible. So far I have 100% working C64 and Atari 800 keyboard matched to the core and I wanted to do the same for the Spectrum and Amstrad CPC next.
