### ISSUE TITLE
Tab not used

### ISSUE THREAD

**Issue by puleyo2000** [MiSTer-devel/ZX-Spectrum_MISTer#29]
Hi @sorgelig,
The spectrum core has not the key TAB assigned.
Could it set to use Graph Mode as like Spectrum plus or 128 ?
So it would be easy to change to [G] mode instead use other combinations.
![image](https://user-images.githubusercontent.com/56347822/126028824-0e92935a-a858-40be-b092-00471661d70d.jpg)
![image](https://user-images.githubusercontent.com/56347822/126028853-b045abe8-1638-4079-8db4-249f9ff1f3dc.jpg)

**Comment by sorgelig** [comment]
should be possible. I will check

**Comment by puleyo** [comment]
Thank you very much !

**Comment by Alessandro1970** [comment]
Hi, this TAB key used as Graph mode would be a great idea.
Me too have been waiting for a WASD keyboard zx keyset.
This is mine:
![63AFB642-AAD9-43B9-BB1B-5D25847A61ED](https://user-images.githubusercontent.com/34916641/127904264-579e1ff9-9138-4154-8699-e880436538c6.jpeg)

**Comment by sorgelig** [comment]
What's up with space key?

**Comment by Alessandro1970** [comment]
The space key is ok with the Mister.
If you mean the red circle on the space key …it is only a old photo that I have on the phone.

**Comment by sorgelig** [comment]
should be done now

**Comment by puleyo** [comment]
Thank you
