### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#30]
@sorgelig 

Hi, with mister, new release, I do not succeed in loading these two games, but with fuse or other emulators they work well.
They hang at the loading.
What kind of problem is there ?

[Terramex [48-128K].tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6982740/Terramex.48-128K.tap.zip)

[Terra Cresta [48-128K].tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6982741/Terra.Cresta.48-128K.tap.zip)

**Comment by sorgelig** [comment]
these files have wrong extension.
They are TZX, not TAP

**Comment by Alessandro1970** [comment]
Ok, I changed to tzx and these two now are working.
This does not work with these three:
[Aftermath [48-128K].tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6986196/Aftermath.48-128K.tap.zip)

[Atomic RoboKid [48-128K].tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6986197/Atomic.RoboKid.48-128K.tap.zip)

[Aliens [48K].tap.zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/6986198/Aliens.48K.tap.zip)

**Comment by Alessandro1970** [comment]
Ok, all these games were downloaded from the wrong site.
Updated all, they works well.
Thanks
