### ISSUE TITLE
Mask tzx hangs

### ISSUE THREAD

**Issue by Alessandro1970** [MiSTer-devel/ZX-Spectrum_MISTer#32]
Hi, 
this is the last game that I do not succeed in running on Mister:

[Mask (1987)(Gremlin Graphics)(128k).zip](https://github.com/MiSTer-devel/ZX-Spectrum_MISTer/files/7101644/Mask.1987.Gremlin.Graphics.128k.zip)

Could you tell me the way to run it or is there any other kind of problem ?

Bye

**Comment by seinsinnes** [comment]
This game is quite a process to load. Seems like a fairly involved non-standard loader.
It takes me about 5 minutes to get into the game.

This is what works for me:

1. Turn off "Fast Tape Load" in the OSD
2. Load the Mask tzx in the OSD
3. Choose "Tape Loader" from menu
4. Press F1 to "stop" the tape when the screen says "Stop the tape". (After starting picture screen.) (~3 mins)
5. Setup controls
6. Press F1 to "play" the tape again when the screen says "Press Play" (~1 min)
7. Press F1 to "stop" the tape when the screen says "Stop the tape"
8. It will show you the high scores. Press enter.
9. Press F1 to "play" the tape when the screen says "Press Play"
10. Press F1 to "stop" the tape when the screen says "Stop the tape" (~1 min)
11. Press enter and you're in the game.

**Comment by Alessandro1970** [comment]
You are a wizard !
Thank you
