### ISSUE TITLE
Document boot.rom structure

### ISSUE THREAD

**Issue by jameshpdp** [MiSTer-devel/ZX-Spectrum_MISTer#39]
Hello!

Could we get a few words in the README.md about the boot.rom structure and sources, please? We were able to identify most of the components [1, 2], however some of them appear to be modified. It would be great describing the reason for those modifications, if possible.

Apologies for not starting with a pull request, but I am afraid I do not have enough information for that yet. Happy to draft one when more information is available.

Thank you.

1. https://misterfpga.org/viewtopic.php?p=60600#p60600
2. https://misterfpga.org/viewtopic.php?p=73638#p73638

**Comment by sorgelig** [comment]
I think that info should be correct in [1]. I didn't document it even for my self. ROM set just grew with evolution of core :)

**Comment by jameshpdp** [comment]
Thanks a lot for reviewing (and merging) the doc update!

I am wondering if you remember the +D patching process. If you have some time, could you please review https://misterfpga.org/viewtopic.php?p=73745#p73745 ? Does it make any sense?

**Comment by sorgelig** [comment]
Ok. Commented there.
