### ISSUE TITLE
[Feature Request] Option for disable AY chip

### ISSUE THREAD

**Issue by mambrino** [MiSTer-devel/ZX-Spectrum_MISTer#43]
It would be interesting, in 128k modes, to be able to disable the AY sound chip from the menu, just as it can be done with general sound. Yes, I know that this chip is part of these models, but there are situations in which you want to hear only the beeper sound, because the music is repetitive or for simply comparison, and it's not possible since it is always enabled.

**Comment by sorgelig** [comment]
Ok

**Comment by mambrino** [comment]
great! thank you very much. I have tried to compile the changes in the unstable branch and it works perfectly, but it sounds when it's disabled and vice versa. Shouldn't it work that way, right, or maybe it was my problem compiling?
