### ISSUE TITLE
Multicolor game 'Gluf' not working properly - 128K timing problem?

### ISSUE THREAD

**Issue by mambrino** [MiSTer-devel/ZX-Spectrum_MISTer#46]
Multicolor game [Gluf 128K](https://spectrumcomputing.co.uk/entry/34649/ZX-Spectrum/GLUF) is not working properly. Color lines become mismatched and the image is confusing.
Maybe it has to do with 128k mode timings, usually the cause of these multicolour routines to fail.
Tested in fuse and zxnext core too and work perfectly.

**Comment by mambrino** [comment]
sorry, tested with another config and works ok

**Comment by gyurco** [comment]
The TRD version is for Pentagon.
The tape version is for 128k.

**Comment by mambrino** [comment]
yes, but in addition for the 128 version to work you have to disable fast tape loading, and I had it enabled.
Thanks ;)
