### ISSUE TITLE
Sound corrupted with 128k only games

### ISSUE THREAD

**Issue by foxp4v** [MiSTer-devel/ZX-Spectrum_MISTer#6]
Hello, i'm a new user of MisTer, trying this core i've encountered a possible bug, trying one of my favourite homebrew game: Castlevania Spectral Interlude, freely downloadable on the authors page http://spectralinterlude.com/ i've seen that the music and the sound in general is horribly corrupted, the same things happens with the game Midnight Resistance with the 128k only version. 48k games i've tried sounds correctly. I'm using HDMI connection and i've tried both 96k and 48k for hdmi audio.

**Comment by sorgelig** [comment]
What's the difference in music between 128K and 48K?  48K is beeper music while 128K is AY music? Or both AY?

**Comment by foxp4v** [comment]
Castlevania use AY, it's written on their site at the system requirements,
the other ones i'm not sure.

Il mar 11 giu 2019, 07:53 sorgelig <notifications@github.com> ha scritto:

**Comment by sorgelig** [comment]
i've listened Castlevania title song and didn't find the difference from OST on site.

**Comment by foxp4v** [comment]
Look at this video i made yesterday:

https://youtu.be/-M48xTfuMzY

Il mar 11 giu 2019, 08:33 sorgelig <notifications@github.com> ha scritto:

**Comment by foxp4v** [comment]
Wait! I've tried ti delete core and ti reinstall and now works! Don't know
wath happened, thanks for your time.

Il mar 11 giu 2019, 09:07 Fortunato Pavone <pavone.fortunato@gmail.com> ha
scritto:
