### ISSUE TITLE
No reset option in OSD 

### ISSUE THREAD

**Issue by ArchiveRL** [MiSTer-devel/ZX-Spectrum_MISTer#9]
In OSD, it's not possible to reset the current machine without changing to another one. 

Eg, if I'm in 48K mode and want to reset I need to first change the machine in "Memory" tab, then "Reset & Apply" becomes available, then I have to change the machine back to 48K in "Memory" and reset again.

I know there are shortcuts for keyboard reset, but it can be a minor annoyance when using a joypad. Perhaps adding a separate "Reset" option would be a good idea, or just enabling "Reset & Apply" to reset current machine without changing it.

**Comment by sorgelig** [comment]
i wanted to fix it in current release but forgot.
will fix it.

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!

**Comment by ArchiveRL** [comment]
I just saw that, thank you! Update first, post later. Sorry!
